### ISSUE TITLE
Can't use arrow keys for controlling gamma

### ISSUE THREAD

**Issue by stantios** [Sjouwer/gamma-utils#15]
I tried to control my gamma using the arrow keys but it didn't work and my gamma didn't go up or down.

**Comment by Sjouwer** [comment]
Do you have another mod that might be using those keys too? Could you try binding different keys to the gamma increase and decrease in the keybinds settings?

**Comment by stantios** [comment]
No, I don't have any mods that conflict or use those keys at all. Also, I tried with other keys and it worked

**Comment by Sjouwer** [comment]
If binding them to other keys works, then I still suspect a conflict with another mod. Some mods use different ways to bind keys, which might cause issues. Since I use the default fabric keybind api there is little I can do about this. I guess you'll just have to use different keys for increasing and decreasing the gamma
