### ISSUE TITLE
Word turns dark.

### ISSUE THREAD

**Issue by Xrey274** [Sjouwer/gamma-utils#4]
Could be caused by Sodium.
![image](https://user-images.githubusercontent.com/30723811/143477232-3b97ff92-abbe-48bb-9adf-b7fbe64989d3.png)

**Comment by Sjouwer** [comment]
I've never seen this myself, could you provide a bit more information?
Which mc version do you play on?
Which gamma value did you use?
Do you have any other mods that might influence the lighting?

**Comment by Xrey274** [comment]
I have Sodium and Phosphor, which could potentially be causing this. Anything above 100, replicates this issue. As for version 1.17.1, up to date fabric loader and api.

**Comment by Xrey274** [comment]
Colormatic as well

**Comment by Sjouwer** [comment]
I've been unable to reproduce the issue when using the same mods.
I doubt it's related to this mod, especially since all this mod does is change the gamma value.
It seems like there have been a couple of issues for Phosphor (closed now) that seem very similar to what you're experiencing.
So my guess this is something related to that.

https://github.com/CaffeineMC/phosphor-fabric/issues/43
https://github.com/CaffeineMC/phosphor-fabric/issues/33

**Comment by Xrey274** [comment]
Hello, a couple of months later I have found the culprit. It's Colormatic. You can rest easy now. lmao

**Comment by Sjouwer** [comment]
Thank you for letting me know.
I'm kinda surprised that's the one that caused it, although now that I look better at the description of that mod I see it also changes lightmaps, which probably is related.
In any case, good to hear that you've found the issue.

I'll leave this mention behind for the mod maker:
https://github.com/kvverti/colormatic/issues/77
